version: '3.5'
services:

  app:
    build: .
    image: &app app
    restart: "no"
    command: ["python", "TaskApi.py", "runserver", "0.0.0.0:4555"]
    env_file: &envfile
      - env.env
    ports:
      - "4555:4555"
    volumes:
      - ./app:/app
    depends_on:
      - broker

  worker:
    build: 
      context: .
      dockerfile: Dockerfile1
    restart: "no"
    env_file: *envfile
    volumes:
      - ./app:/app
    depends_on:
      - broker

  broker:
    image: rabbitmq:3
    env_file: *envfile
    ports:
      - 5672:5672